### ISSUE TITLE
This project fucking rocks!

### ISSUE THREAD

**Issue by ProLoser** [kasperlewau/angular-bind-notifier#10]
Sorry, I just was talking to my coworker about your tests on ui-mention and found this repo. This is fucking awesome, as this entire spec is what I actually proposed as an alternative to static-bindings half a year prior to the Aug 2014 proposal (I referred to them as namespaced-bindings): https://github.com/angular/angular.js/issues/6354

Anyway, I'm going to be following this project closely! :+1: :100:

**Comment by ProLoser** [comment]
Wait. you responded to that issue like a year ago lol. Nvm I will delete this I am sorta flaky on memory apparently.

**Comment by kasperlewau** [comment]
Thanks man, that is very uplifting to hear - regardless of flakiness of ones memory! :smile:
