### ISSUE TITLE
controllerAs?

### ISSUE THREAD

**Issue by kasperlewau** [kasperlewau/angular-bind-notifier#12]
not sure how this currently plays out with the `controllerAs` way of doing things. will probably want to support this at some point if it doesn't.

**Comment by szuzul** [comment]
I successfully implement bind-notifier with controller as syntax on collection-repeat and it works without rising number of watchers on view. 

 <ion-content class="interests-box">
            <ion-refresher pulling-text="Pull to refresh..." on-refresh="vm.refreshFriends()"></ion-refresher>
            <div class="home-event-list-empty home-event-list-empty--my-events"
                 ng-include="'js/modules/home/event-list-empty.html'" ng-if="!vm.getAllFriends().length"></div>

            <ion-list class="__friend-list" ng-if="vm.getAllFriends().length > 0">
                <ion-item class="item-avatar friend" collection-repeat="friend in :refresh:vm.getAllFriends()">
                  <img src="{{:refresh:friend.profileImage[0].path}} "/>

                  <div class="friend __list-header">{{:refresh:friend.name}}</div>
                  <div class="__body-item __interests">
                    <div class="__interest-list">
                      <div class="__interest" ng-repeat="interest in friend.commonInterests">
                        #{{::interest.interesModel.name}}
                      </div>
                    </div>
                  </div>
                </ion-item>
            </ion-list>
          </ion-content>
