### ISSUE TITLE
bug: after updating to 1.1.3 breaking when uglified

### ISSUE THREAD

**Issue by stephenlautier** [kasperlewau/angular-bind-notifier#14]
Hi,

Today I've updated my project to version `1.1.3` up from `1.1.1` (actually semver did) and I've noticed that when the library is being uglified its now breaking. I've also tested the 1.1.2 and its working fine as 1.1.1 used to be.

By breaking I mean:
- no errors appears
- simply not refreshing
- without uglified everything works fine

**Note:** We are using the `src/bindNotifier.js`, since then we bundle/uglify all vendors together ourselves.

**Update:** I was just seeing the commits and this might look to be the culprit https://github.com/kasperlewau/angular-bind-notifier/commit/03cc20f9bd3d1c4b77e473bc79ff91e20772e5b5#diff-1d91badbc52faa5f1605b75be34bd83eR66

**Update2:**
Debugged a bit and added screenies

#### Non-uglified
![2015-10-28 19_17_33-sports betting amp for football hockey basketball tennis _ betsson](https://cloud.githubusercontent.com/assets/3908723/10798598/b7199ef6-7da8-11e5-8508-f3a771b1eb15.png)

#### uglified
![2015-10-28 19_12_34-odds - betsson](https://cloud.githubusercontent.com/assets/3908723/10798601/b9dde606-7da8-11e5-99a2-aeab2c9dd288.png)

**Comment by kasperlewau** [comment]
Myeah, this has to do with minified versions of angular. sowwy. 

Will get on it asap.

**Comment by kasperlewau** [comment]
Good catch by the way - thanks for the detailed issue!

**Comment by stephenlautier** [comment]
You're welcome :)

**Comment by kasperlewau** [comment]
Would you mind trying out the source as found [here](https://raw.githubusercontent.com/kasperlewau/angular-bind-notifier/fix/broken-notifications/dist/angular-bind-notifier.min.js)? 

It's even less to my liking in terms of what we're doing as far as conditional checks go. But, again - it *seems* to work.

**Comment by kasperlewau** [comment]
It's also used at [gh-pages](https://github.com/kasperlewau/angular-bind-notifier) for the time being.

**Comment by stephenlautier** [comment]
I can give it a go tomorrow as I don't have the source with me.

> gh-pages 

Link provided is broken but I think you meant http://kasperlewau.github.io/angular-bind-notifier/ correct?

**Comment by kasperlewau** [comment]
Precisely, sorry.
ons 28 okt 2015 kl. 21:39 skrev Stephen Lautier <notifications@github.com>:

> I can give it a go tomorrow as I don't have the source with me.
>
> gh-pages
>
> Link provided is broken but I think you meant
> http://kasperlewau.github.io/angular-bind-notifier/ correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kasperlewau/angular-bind-notifier/issues/14#issuecomment-151983756>
> .
>
-- 
Kasper Lewau - Angular Developer
Rushplay AB

+46 720 22 24 47

Östervärnsgatan 10A
21218 Malmö

github.com/kasperlewau

**Comment by kasperlewau** [comment]
Reopening this as there are some unsolved cases revolving the usage of `.bind` in conjunction with polyfills/minified sources. 

It's starting to become quite cumbersome to test for truthiness of that the given watchDelegate is that of a oneTimeWatchDelegate.

**Comment by kasperlewau** [comment]
Closed by fabf9ea6308ccbe6519f76c0a5e93fcc65e79bda

**Comment by stephenlautier** [comment]
I've just tested this out, its working correctly as intended, thanks! :+1:
