### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by Anahkiasen** [kasperlewau/angular-bind-notifier#2]
Package currently can't be installed through NPM, although it seems all ready for it

**Comment by kasperlewau** [comment]
Done! 

https://www.npmjs.com/package/angular-bind-notifier.

I'll modify the README ever so slightly to add a note about npm installation, although the package has not been transfered over to a common format.

**Comment by kasperlewau** [comment]
Closing this one for now. If you would like for the package to be available as a CommonJS module, a feature request / PR(yes plz!) is more than welcome.
