### ISSUE TITLE
Some way to refresh property of only one element in ng-repeat?

### ISSUE THREAD

**Issue by xingped** [kasperlewau/angular-bind-notifier#24]
So say you have:

```
<div ng-repeat="e in elements">
  <span>e.name</span>
  <span>:typeRefresh:e.type</span>
</div>
```

When you do a `$scope.$broadcast('$$rebind::typeRefresh');` it's going to refresh the e.type of all items in the elements array, right? Is there some way to trigger a refresh on the property of only one item in the ng-repeat?

**Comment by kasperlewau** [comment]
> When you do a $scope.$broadcast('$$rebind::typeRefresh'); it's going to refresh the e.type of all items in the elements array, right?

**Correct!**

> Is there some way to trigger a refresh on the property of only one item in the ng-repeat?

If you were to use the `bind-notifier="{}"` directive, you could set it up to work on *some* of the repeated items using the supplied `$index/$last/$middle/$even/$odd` operators. 

Like so; 

```html
<div ng-repeat="i in items">
  <div ng-if="$even" bind-notifier="{ refresh: someExpression }">
    <span>{{:refresh:i}}</span>
  </div>
  <div ng-if="$odd">
    <span>{{::i}}</span>
  </div>
</div>
```

Though that would defeat the purpose of the library to some extent as you would introduce a lot more watchers. 

--- 

The short story; No, there is currently no way to filter a rebind namespace to a single item / subset of items. 

Off of the top of my head, I don't see how this would be implemented. The broadcaster of the event would need to have some sort of awareness of all of the items that match the given namespace and only target a subset of them. Effectively shuffling the responsibility over to the broadcaster, from the receiver.

**Comment by kasperlewau** [comment]
Closing this one for now.
