### ISSUE TITLE
Incorrect behaviour when using with filter containing arguments

### ISSUE THREAD

**Issue by magaman384** [kasperlewau/angular-bind-notifier#27]
When using angular-bind-notifier inside with filter that contains arguments, first filter's argument is rendered instead of actual value with applied filter.

e.g.: `{{:data: value | currency: '$' }}` renders `$` instead of `$2.00`
jsbin: http://jsbin.com/vufehiceyi/1/edit?html,js,output

When there are no arguments it works correctly. Maybe the parser is not treating the colon properly?

**Comment by kasperlewau** [comment]
You're right on the money. I'm very sorry for not being around as much as I'd like to. There's an [open PR](https://github.com/kasperlewau/angular-bind-notifier/pull/26) that I reckon I should *probably* merge tonight that'll take care of this issue.
