### ISSUE TITLE
Expression throws error

### ISSUE THREAD

**Issue by arashb31** [kasperlewau/angular-bind-notifier#28]
When I have my expression like such:

`{{ :refresh:user.name }}
`
I receive this error:

Syntax Error: Token ':' not a primary expression at column 1 of the expression [:refresh::user.name] starting at [:refresh::user.name].

However, if I remove the leading space, it works. Is this intended behaviour?

e.g.
`{{:refresh:user.name}}
`

**Comment by arashb31** [comment]
Also, should this expression still work:

`{{:refresher::user.name}} 
`

**Comment by kasperlewau** [comment]
> However, if I remove the leading space, it works. Is this intended behaviour?

That is not the intended behaviour, no. I'll see if I can get on that in a timely fashion (basically means I'll pester @tregusti about some assistance), I've got a feeling it has to do with some of the regexes in use. 

> Also, should this expression still work: {{:refresher::user.name}} 

No, that will not work 😄

**Comment by tregusti** [comment]
You solved that nicely! Though you could remove the brackets around the \s in a future commit. Not needed, but no diff.
