### ISSUE TITLE
Watchers being constantly created

### ISSUE THREAD

**Issue by mp-tbianchi** [kasperlewau/angular-bind-notifier#31]
Hi,

I've been using bind-notifier for a project I'm working on. I need to display thousands of lines so I need to be careful on how I generate the data.

https://plnkr.co/edit/4tWoNYeZlGFbCC3svKxP?p=preview

Here you can see I have `vm.data` that contains the full data and `vm.display` that only contains the data to display.
When I click on an Id, I add the corresponding data to the display object.

If you toggle several times any object, you can use the 'Count' button to see the watchers increasing every time.

Any idea why?

Thanks!

**Comment by kasperlewau** [comment]
@mp-tbianchi There seems to be an issue with the bind-notifier in conjunction with a nested usage of `ng-repeat-start`. 

I managed to solved it in your plunker by removing the nested notifier syntax. As such; 

```html
<tr ng-repeat-start="item in :superduper:controller.foo">
  <tr ng-repeat-start="other in superduper:controller.bar">
  <tr ng-repeat-end></tr>
<tr ng-repeat-end></tr>
```

[plunker](https://plnkr.co/edit/AQzXeDlYCsodOwEGCZY2?p=preview)

**Comment by mp-tbianchi** [comment]
Thank you for your quick answer!

I can make do with this workaround for now but this example was simplified.  
Do you think there will be a way in the future to use nested notifiers with ng-repeat-starts?

For example, I may need need to use different notifier names to update only this or this section or maybe the whole table.

**Comment by kasperlewau** [comment]
I'd need to look into it further to get a feeling for _what_ is going wrong with ng-repeat-start/end, but it is definitely something we'd like to support. 

I just need to find some time on my hands to dig in..

**Comment by mp-tbianchi** [comment]
I see, thanks for your help. When I have time, I'll try and look into it too.

**Comment by kasperlewau** [comment]
Closing this for now.
