### ISSUE TITLE
Ternary operation

### ISSUE THREAD

**Issue by GustavoCostaW** [kasperlewau/angular-bind-notifier#32]
Hey, guys, I appreciate this amazing directive, congratz for work.

But I have problems using a simple ternary operator:

e.g:
```
{{:refresh:vm.check ? :refresh:vm.opc1 : :refresh:vm.opc2}} // Error: $parse:syntax
Syntax Error
```

Exist another way to use ternary? Thank you.

**Comment by GustavoCostaW** [comment]
I'm using manual $broadcast.

**Comment by lrajlich** [comment]
check this PR https://github.com/kasperlewau/angular-bind-notifier/pull/25

**Comment by GustavoCostaW** [comment]
@lrajlich thx for link, I changed to automatically mode and works.
