### ISSUE TITLE
Multi-line object expression parsing problems.

### ISSUE THREAD

**Issue by 0x4C4A** [kasperlewau/angular-bind-notifier#37]
During development I like to write some longer ng-class expressions multi-line. The current regex doesn't support that.
What I mean is:
This works - 
`    <div ng-class=":refresh:{'red' : test, 'blue': !test}">`
`      {{:refresh:test}}`
`    </div>`

This doesn't - 
`    <div ng-class=":refresh:{'red' :  test , `
`                             'blue': !test}">`
`      {{:refresh:test}}`
`    </div>`

[jsbin demo](https://jsbin.com/memukumegi/edit?html,css,js,output)

**Comment by kasperlewau** [comment]
Closed by #38
