### ISSUE TITLE
manual refresh causing "$$refresh" to be registered exponentially

### ISSUE THREAD

**Issue by stephenlautier** [kasperlewau/angular-bind-notifier#5]
Hi,

Basically I seem to found an issue which is causing to adding $$refresh listeners exponentially, while using manual refresh.

I've got a jsbin with a repro: http://jsbin.com/quromeqihi/1/edit?html,css,js,output

This is how it should be tested:

- Go to http://jsbin.com/quromeqihi/1/edit?html,css,js,output
- Add a break point on angular.js on line 14766 ($broadcast)
- Press Add from the UI
- See the target.$$listenerCount
- Keep doing the above e.g. Add and check count
They `target.$$listenerCount` keep increase exponentially.

Thanks!

**Comment by kasperlewau** [comment]
I've attempted to play around with the implementation of bind-notifier here, but no sauce. 

Obviously killing the call to `watchDelegate` and/or not returning anything from `dynamicWatcher`, kills the $$listenerCount. 

**However** - when switching from: 

`ng-class=":refresh:classFunc()"` into `class="{{:refresh:classFunc()}}" - the $$listenerCount is proportional to the amount of DOM nodes. 

I'm not sure *what* exactly ng-class is doing here in conjunction with bind-notifier, but it does appear to increase the $$listenerCount exponentially.

**Comment by stephenlautier** [comment]
Actually your workaround makes me happy, by using the following:
```
class="{{:refresh:classFunc()}}"
```
So now I can use this plugin  :+1: . I will ask you another question in a different issue if you can help.

Thanks again!

**Comment by stephenlautier** [comment]
Just an update on this one, it doesn't simply happen on `ng-class`, I have a very simple directive with a scope parameter as `'='`, happens the same exact thing.

Also created a jsbin for it with a sample:

http://jsbin.com/gocaduqati/1/edit?html,js,output

So when having scope param as `valChange: "="` and bind it as `val-change=":refresh:person.name"` it leaks.
However when having scope param as `valChange: "@"` and bind it as `val-change="{{:refresh:person.name}}"` it doesn't.

Its been causing me some trouble when trying to use it in several places unfortunately due to this issue

**Comment by kasperlewau** [comment]
Been doing some testing here, trying to figure out what is actually going on. 

So far, no real conclusions apart from the fact that utilising the `:ns:expr` syntax in a 'by-nature' two-way bound context will run the `addListener` function multiple times as $parse is being called internally when trying to evaluate the expression of the context. 

As such, I would strongly recommend that; 

* If you want to re-evaulate *someTimes*, use the `:ns:expr` syntax but **outside** of `ng-class` and `=`. Those are the two identified outliers so far, I'll try to compile a list of all the common ng directives that don't play well with this. 
* If you want to re-evaluate more often, scrap the usage of `:ns:expr` and go with the standard Angular supplied 'stuff'. 

**tbc.**

**Comment by kasperlewau** [comment]
@stephenlautier 

I've made some tinkering tonight and *finally* I've managed to kill the exponential addition(s) of $$listeners. At least, I think I have. 

Basically I'm just doing a check in the `dynamicWatcher` to ensure that the given `watchDelegate` has a prototype (the fuck?)(this could be taken a step further to ensure the prototype is `oneTimeWatchDelegate`), and for some reason in the case of ng-class/etc the prototype appears to have been lost. I would bet that has to do with the $parse decorator itself. In any case, exponential no more. 

Would you mind giving it a run for it's money?

Take [the following raw content from the fix/exponential-listeners](https://raw.githubusercontent.com/kasperlewau/angular-bind-notifier/fix/exponential-listeners/src/bindNotifier.js) branch and plug it into your plunker(s). 

*It's all pretty freaky and at this point my brain is mush - I'm not a hundred percent certain on what is going on behind the scenes.*

**Comment by kasperlewau** [comment]
[updated jsbin](http://jsbin.com/velipaqive/1/edit?html,js,output)

**Comment by stephenlautier** [comment]
Just seen your comments, I've tested it out a bit within the jsbin. Its looking good! :+1:

**Comment by kasperlewau** [comment]
Closed by #11
