### ISSUE TITLE
Refresh all one time by namespace

### ISSUE THREAD

**Issue by stephenlautier** [kasperlewau/angular-bind-notifier#6]
Hi,

Not sure if I'm asking too much, however I'm trying to see if its possible to have the following (not sure if it make sense):
 - Have a ng-repeat
 - within the ng-repeat bind with a namespace e.g. `:refresh:persons`
 - Refresh all the bind once, descendants

Example below
http://jsbin.com/sefomorura/edit?html,css,js,output

I've created a jsbin with the example, as you can see `::isSelected` doesn't refresh, however when adding a new item that one does (probably because I have the namespace on the ng-repeat). Is it possible to have something like that?

The reason is to remove all watchers within the list and then control how they gets refreshed without having to do `:refresh:` with every binding.

Thanks, once again.

**Comment by kasperlewau** [comment]
That isn't necessarily a bad idea, and I'm sure a lot of people would appreciate it. 

However, that would completely exclude the possibility of having a one-time binding inside the scope of a bind-notifier. Which is not something we want. 

I would not rule out the ability to refresh one-time binds that are bound to expressions *matching* the given namespace. 

Such as; 

```html
<div bind-notifier="{person: personExpr}">
  <span>{{::blabla}}</span>
  <span>{{:person:blabla}}</span>
  <span>{{::person.prop}}</span>
</div>
```

The first binding would not be refreshed, whereas the two last ones would. But this is not a priority as of now, with that said I am of course accepting pull request(s) that would implement this. 

--- 

As for the jsbin, no there is currently no way to get a bind-notifier namespace to refresh one time bindings. 

I've made some small edits to your example that I think will fit the bill in your case: http://jsbin.com/lerizuhose/1/edit

**Comment by stephenlautier** [comment]
Thanks for you kind+quick replies. Sorry for posting a lot but liked this module :+1:.
